### ISSUE TITLE
Request : invert movement axis setting

### ISSUE THREAD

**Issue by Mr5quid** [raatmarien/Point-and-Hit#2]
Hi there !

I like your game ! I'm terrible at it though haha. That's partly because for some reason I instinctively tend to tilt the  phone in the opposite direction. Therefore it would be nice to have the option to invert the axiss :).

**Comment by raatmarien** [comment]
Hi!

Happy you like it :). I realize it has a very steel learning curve, that's mostly because I got way to good at it while testing the game myself :P.

Thanks for the feedback, I'll look into adding an option to invert the axis.

**Comment by raatmarien** [comment]
I added an option to invert the controls in the settings. However, it automatically sets normal sensitivity for now, I hope that's okay.

A new version with this feature will probably be available on F-droid in a few days.
